services:
  # 1. Backend Web Service (Node.js Express API)
  - type: web
    name: contacthub-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: key
        value: ak47
      - key: MONGODB_URL
        value: mongodb+srv://ANUJ5599:aa2602@db.xwyqugi.mongodb.net/?appName=DB
      - key: CLOUD_NAME
        value: dwlc9djom
      - key: API_KEY
        value: 226873333856178
      - key: API_SECRET
        value: bDfW69XH53oAZ8_whDumlra_de4

  # 2. Frontend Static Site (React Vite)
  - type: web
    name: contacthub-app
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://contacthub-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
